# Generated by Django 3.2.8 on 2023-09-17 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_student_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='points',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
