# Generated by Django 3.2.8 on 2023-09-20 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_student_points'),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='badges/')),
                ('points_required', models.PositiveIntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='badges',
            field=models.ManyToManyField(blank=True, to='accounts.Badge'),
        ),
    ]
