# Generated by Django 3.2.8 on 2023-09-22 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alphabet', models.CharField(blank=True, max_length=1)),
                ('word', models.CharField(max_length=50)),
            ],
        ),
    ]
