# Generated by Django 3.2.8 on 2023-09-24 01:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_phoneme'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(blank=True, upload_to='sign_videos/')),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.word')),
            ],
        ),
    ]
